mherrmann/gitignore_parser

gitignore_parser.py
The following warning was being produced:
```
gitignore_parser.py:118: DeprecationWarning: Flags not at the start of the expression 'XYZ' (truncated) if re.search(self.regex, rel_path):
```
We probably could use the 3rd argument of `re.search` but that looks like more work than I have time for at the moment.
=> Fixed deprecation when modifiers are at the end of a 're' expression

gitignore_parser.py, setup.py
Fix for fatal error appearing on Windows when you try to use current version of module - re throws an error about unterminated characters because of insufficient escaping (`os.sep` is indeed escaped for python purposes, but on Windows re needs double escaping). Furthermore, re doesn't seem to operate on a few expressions used in current version (as they are part of extended perl-like set, e.g. '\Z') so I changed it to third-party regex - it's fully backward-compatible. In addition to error fix, now the module is more windows-compatible as it supports os.altpath.
=> Windows bug fix and compatibility

setup.py
Even if designed for python3, gitignore_parser perfectly works with python2, except that pathlib is not provided by default with python2.
(Yes, I know, python2 is dead...)
=> Add pathlib as required (for python2 usage)

gitignore_parser.py, tests.py
In this commit, I fixed two things: negation rules and trying to parse
"**" when the pattern has only one "*".
To make negation rules work, I had to add a completely separate method
for rule evaluation. You can't use Python any() to evaluate rules since
later rules override earlier rules. Instead, I had to go through the
rules one by one and have later rules (if they are negation rules)
override earlier matches. There's a handle_negation() method that does
this.
I also changed the pattern parsing to check for two characters before it
tries to evaluate "**". It seems to fix the bare "*" rule, but more
testing is needed.
Fixes: https://github.com/mherrmann/gitignore_parser/issues/12
=> Fix negation rules and ** parsing.

tests.py
- Avoid using tmp file in tests and mock the IO
=> Use mock_open instead of tmp file

gitignore_parser.py, tests.py
Hi.
I'm happy to tell that you have one more dependent project now, it's https://github.com/excitoon/3 — `tree` replacement. I've found some bugs while testing.
Kind regards,
Vladimir.
=> Added test ignoring all subdirectories

gitignore_parser.py, tests.py
While integrating your library I found one case that is a mismatch with how `.gitignore` works. It relates to support of directory-only negation - useful thing when you want to discard some spool dir, but keep the directory structure in the version control. The feature is used by Kedro framework [in their proejct template](https://github.com/kedro-org/kedro/blob/main/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/.gitignore#L13):
```
data/**
!data/**/
!.gitkeep
```
and makes it easy to store the structure of `data/` subdirs in git:
```
$ tree -a data/
data/
├── 01_raw
│   └── .gitkeep
├── 02_intermediate
│   └── .gitkeep
├── 03_primary
│   └── .gitkeep
├── 04_features
│   └── .gitkeep
├── 05_model_input
│   └── .gitkeep
├── 06_models
│   └── .gitkeep
└── 08_reporting
└── …
```
=> Support for directory-only negation

gitignore_parser.py, tests.py
=> Ensure that `Path` type is supported in `matches()`

gitignore_parser.py, tests.py
Fixes https://github.com/mherrmann/gitignore_parser/issues/45
Added a test to show the issue that's fixed by this PR.
e.g.
If there is a rule:
```
.venv/
```
Then also files called `.venv_file.py` or `.venv_other_directory` are matched.
=> Fix directory rule matching similar files

gitignore_parser.py
The utility function `handle_negation` can be optimized to return early if we iterate over `rules` in reversed order.
In the previous implementation, `handle_negation` always iterates over all `rules` to find for matches. However, since later rules take precedence, we can perform the search in reversed order and return early.
This pull request is a performance improvement and should not change behavior, as verified by the tests.
=> perf: optimize `handle_negation` to check rules in reversed order

.github/workflows/ci.yml
Fix the name of the CI steps of the `test` job.
The setup step was previously named "Set up Python 3.8", which is misleading since we have a matrix of Python versions to test with. The new name now uses the correct Python version.
The test step previously mentioned `pytest`, which is wrong since we currently use unittest for testing. I chose simply "Run tests" to avoid mentioning any particular testing framework.
=> ci: fix CI step names

setup.py
Since this project only supports Python 3.5+, we don't need the `pathlib` requirement in `install_requires` in `setup.py`.
=> build: remove `pathlib` from `install_requires`

setup.py
Extend the list of supported Python versions up to 3.11 in the `classifiers` in `setup.py`. This shows users that we support Python 3.11, as attested by the CI checks.
=> chore: list Python versions 3.8 to 3.11 in the classifiers

gitignore_parser.py
Remove the variable `whitespace_re`, which is not used anywhere in the codebase.
=> refactor: clean up unused variable

gitignore_parser.py
According to [the official Python docs](https://docs.python.org/3.5/library/re.html#regular-expression-syntax), the regex flags `'m'` and `'s'` correspond to [`re.M`](https://docs.python.org/3.5/library/re.html#re.M) and [`re.S`](https://docs.python.org/3.5/library/re.html#re.S), which only matter when dealing with newlines or multiline strings. Since each ignore rule is a single-line pattern, we can safely remove those flags without any change in behavior.
This might be sufficient for https://github.com/mherrmann/gitignore_parser/pull/11 to work correctly, although I haven't tested it.
=> refactor: remove regex flags

gitignore_parser.py, tests.py
When a slash appears in a range, it should NOT match a directory
separator.
Quoting https://git-scm.com/docs/gitignore#_pattern_format:
> The range notation, e.g. `[a-zA-Z]`, can be used to match one of the
> characters in a range. See `fnmatch(3)` and the `FNM_PATHNAME` flag for
> a more detailed description.
And quoting what `fnmatch(3)` has to say about `FNM_PATHNAME`:
> match a slash in `string` only with a slash in `pattern` and not by an
> asterisk (`*`) or a question mark (`?`) metacharacter, nor by a bracket
> expression (`[])` containing a slash.
Hence, it seems to me that a slash inside a range should be disregarded.
=> Fix pattern with slash in range

gitignore_parser.py, tests.py
Quoting the relevant paragraph in
https://git-scm.com/docs/gitignore#_pattern_format:
>  Put a backslash ("`\`") in front of the first "`!`" for patterns that
>  begin with a literal "`!`", for example, "`\!important!.txt`".
=> Fix patterns with leading exclamation marks

gitignore_parser.py, tests.py
This proposes a different fix to issue #10 than what is currently in
PR #11. Not sure which solution is more correct/preferable.
Commits:
- Fix `DeprecationWarning: invalid escape sequence '\/'`
- Fix lack of implicit anchoring of patterns to directory separators
=> Fix lack of implicit anchoring of patterns to directory separators

gitignore_parser.py, tests.py
Commits
- Fix handling of `**` where it's supposed to be treated like `*`
- Fix handling of `***`, i.e. to be treated like `*`
=> Fix multi-asterisks that fall outside of the special cases

gitignore_parser.py, tests.py
Avoid resolving symlinks when matching gitignore rules. This is compliant with https://git-scm.com/docs/gitignore#_notes.
Fixes https://github.com/mherrmann/gitignore_parser/issues/29.
=> fix: do not resolve symlinks

.github/workflows/ci.yml, setup.py
Python 3.12 was released not too long ago and it would be nice to keep this library current.
This change updates the distributions classifier to include Python 3.12 as being supported. It also adds 3.12 to the CI's testing matrix to test it as well.
=> Add support and testing for Python 3.12
